// src/components/MetricsTable.tsx
import type { ClientMetrics } from "../types";
import { REASON_LABEL } from "./AvailabilityStrip";
import { fmtDuration, fmtPercent } from "../utils/format";

export default function MetricsTable({
  metrics, target, reasons,
}: {
  metrics: Record<string, ClientMetrics>;
  target: number;
  reasons?: Record<string, string>;  // доминирующая причина перерыва по клиенту
}) {
  return (
    <table className="metrics">
      <thead>
        <tr>
          <th>Клиент</th>
          <th>Доступность</th>
          <th>Макс. перерыв</th>
          <th>Основная причина перерывов</th>
          <th>Цель ≥ {fmtPercent(target)}</th>
        </tr>
      </thead>
      <tbody>
        {Object.entries(metrics).map(([cid, m]) => {
          const ok = m.availability >= target;
          return (
            <tr key={cid}>
              <td>{cid}</td>
              <td>{fmtPercent(m.availability)}</td>
              <td>{fmtDuration(m.max_gap_s)}</td>
              <td className="muted">
                {reasons?.[cid] ? (REASON_LABEL[reasons[cid]] ?? reasons[cid]) : "—"}
              </td>
              <td className={ok ? "ok" : "bad"}>{ok ? "✓" : "✗"}</td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}

// app/features/metrics/MetricsTable.vue
<script setup lang="ts">
import type { ClientMetrics } from '~~/shared/types/scenario'

import { fmtDuration, fmtPercent } from '~~/shared/utils/format'
import { REASON_LABEL } from '~~/shared/utils/routes'

import { Badge } from '~/components/ui/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '~/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'

defineProps<{
  metrics: Record<string, ClientMetrics>
  target: number
  reasons?: Record<string, string>
}>()
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Метрики</CardTitle>
      <CardDescription>Сквозная достижимость и перерывы по клиентам</CardDescription>
    </CardHeader>
    <CardContent class="p-0">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Клиент</TableHead>
            <TableHead>Доступность</TableHead>
            <TableHead>Макс. перерыв</TableHead>
            <TableHead>Основная причина</TableHead>
            <TableHead>Цель ≥ {{ fmtPercent(target) }}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="(m, cid) in metrics" :key="cid">
            <TableCell><b>{{ cid }}</b></TableCell>
            <TableCell>{{ fmtPercent(m.availability) }}</TableCell>
            <TableCell>{{ fmtDuration(m.max_gap_s) }}</TableCell>
            <TableCell class="text-mist">{{ reasons?.[cid] ? (REASON_LABEL[reasons[cid]] ?? reasons[cid]) : '—' }}</TableCell>
            <TableCell>
              <Badge :variant="m.availability >= target ? 'default' : 'destructive'">
                {{ m.availability >= target ? '✓' : '✗' }}
              </Badge>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </CardContent>
  </Card>
</template>
