// app/features/scenario/BatchesTab.vue
<script setup lang="ts">
import type { Scenario } from '~~/shared/types/scenario'
import type { ValidationError } from '~~/shared/utils/validate'

import { PlusIcon } from 'lucide-vue-next'

import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Card } from '~/components/ui/card'
import { Field, FieldError, FieldGroup, FieldLabel } from '~/components/ui/field'
import { Input } from '~/components/ui/input'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'

const props = defineProps<{ scenario: Scenario, errors: ValidationError[] }>()
const emit = defineEmits<{ update: [s: Scenario] }>()
const stageId = useId()

const design = computed(() => props.scenario.design)
const sats = computed(() => design.value.satellites)
const stageError = computed(() => props.errors.find(e => e.path === 'design.launch_stage')?.message)
const counts = computed(() => {
  const c: Record<1 | 2 | 3, number> = { 1: 0, 2: 0, 3: 0 }
  for (const s of sats.value) {
    if (s.launch_batch === 1 || s.launch_batch === 2 || s.launch_batch === 3)
      c[s.launch_batch]++
  }
  return c
})

function setStage(stage: 1 | 2 | 3) {
  emit('update', { ...props.scenario, design: { ...design.value, launch_stage: stage } })
}

function updSat(i: number, k: string, v: unknown) {
  const next = sats.value.map((s, k2) => (k2 === i ? { ...s, [k]: v } : s))
  emit('update', { ...props.scenario, design: { ...design.value, satellites: next } })
}

function addSat() {
  const defaultPlane = design.value.planes[0]?.id ?? ''
  emit('update', {
    ...props.scenario,
    design: {
      ...design.value,
      satellites: [...sats.value, {
        id: `S${String(sats.value.length + 1).padStart(2, '0')}`,
        launch_batch: 1 as const,
        plane_id: defaultPlane,
        slot_deg: 0,
      }],
    },
  })
}

function removeSat(i: number) {
  emit('update', {
    ...props.scenario,
    design: { ...design.value, satellites: sats.value.filter((_, k) => k !== i) },
  })
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <div class="flex items-center justify-between">
      <h3 class="text-sm font-medium">Очереди запуска</h3>
      <Button size="sm" variant="secondary" @click="addSat">
        <PlusIcon data-icon="inline-start" />Спутник
      </Button>
    </div>

    <FieldGroup>
      <Field :data-invalid="!!stageError || undefined">
        <FieldLabel :for="stageId">Активная очередь (launch_stage)</FieldLabel>
        <Select :model-value="String(design.launch_stage)" @update:model-value="setStage(Number($event) as 1 | 2 | 3)">
          <SelectTrigger :id="stageId" :aria-invalid="!!stageError || undefined">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectItem value="1">1 — 16 аппаратов</SelectItem>
              <SelectItem value="2">2 — 32 аппарата</SelectItem>
              <SelectItem value="3">3 — все 48</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <FieldError v-if="stageError">{{ stageError }}</FieldError>
      </Field>
    </FieldGroup>

    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>ID</TableHead>
          <TableHead>Плоскость</TableHead>
          <TableHead>Slot, °</TableHead>
          <TableHead>Очередь</TableHead>
          <TableHead class="w-12" />
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow v-if="!sats.length">
          <TableCell colspan="5" class="text-mist">Спутников нет. Нажмите «+ Спутник».</TableCell>
        </TableRow>
        <TableRow v-for="(s, i) in sats" :key="i">
          <TableCell>
            <Input :model-value="s.id" @update:model-value="updSat(i, 'id', String($event))" />
          </TableCell>
          <TableCell>
            <Select :model-value="s.plane_id" @update:model-value="updSat(i, 'plane_id', String($event))">
              <SelectTrigger><SelectValue placeholder="— выберите —" /></SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem v-for="p in design.planes" :key="p.id" :value="p.id">{{ p.id }}</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </TableCell>
          <TableCell>
            <Input type="number" step="0.1" :model-value="s.slot_deg" @update:model-value="updSat(i, 'slot_deg', Number($event))" />
          </TableCell>
          <TableCell>
            <Select :model-value="String(s.launch_batch)" @update:model-value="updSat(i, 'launch_batch', Number($event))">
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="1">1</SelectItem>
                  <SelectItem value="2">2</SelectItem>
                  <SelectItem value="3">3</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </TableCell>
          <TableCell>
            <Button size="sm" variant="destructive" @click="removeSat(i)">−</Button>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>

    <div class="flex gap-2">
      <Card v-for="b in ([1, 2, 3] as const)" :key="b" class="flex-1 p-3 text-xs">
        <b>Очередь {{ b }}</b>
        <span> — {{ counts[b] }} аппаратов</span>
        <Badge v-if="design.launch_stage >= b" variant="secondary" class="ml-2">включена</Badge>
        <span v-else class="ml-2 text-mist">выключена</span>
      </Card>
    </div>
  </div>
</template>

// src/components/BatchesTab.tsx
import { Field, ListHeader } from "./Field";
import type { Scenario } from "../types";
import type { ValidationError } from "../utils/validate";
import { errorsForItem } from "../utils/validate";

export default function BatchesTab({
  scenario, errors, onChange,
}: {
  scenario: Scenario;
  errors: ValidationError[];
  onChange: (s: Scenario) => void;
}) {
  const d = scenario.design;
  const sats = d.satellites;
  const planes = d.planes;

  function setStage(stage: 1 | 2 | 3) {
    onChange({ ...scenario, design: { ...d, launch_stage: stage } });
  }

  function updSat(i: number, k: string, v: any) {
    const next = sats.map((s, k2) => (k2 === i ? { ...s, [k]: v } : s));
    onChange({ ...scenario, design: { ...d, satellites: next } });
  }

  function addSat() {
    const defaultPlane = planes[0]?.id ?? "";
    onChange({
      ...scenario,
      design: {
        ...d,
        satellites: [...sats, {
          id: `S${String(sats.length + 1).padStart(2, "0")}`,
          plane_id: defaultPlane,
          slot_deg: 0,
          launch_batch: 1,
        }],
      },
    });
  }

  function removeSat(i: number) {
    onChange({
      ...scenario,
      design: { ...d, satellites: sats.filter((_, k) => k !== i) },
    });
  }

  // группировка по launch_batch
  const batches: Record<1 | 2 | 3, { sat: any; idx: number }[]> = {
    1: [], 2: [], 3: [],
  };
  sats.forEach((s, idx) => {
    if (batches[s.launch_batch as 1 | 2 | 3]) {
      batches[s.launch_batch as 1 | 2 | 3].push({ sat: s, idx });
    }
  });

  const stageError = errors.find(e => e.path === "design.launch_stage")?.message;

  return (
    <div className="tab-pane">
      <ListHeader title="Очереди запуска" errors={errors} onAdd={addSat} />

      <div className="stage-select">
        <Field error={stageError}>
          <label>
            Активная очередь (launch_stage):&nbsp;
            <select value={d.launch_stage}
                    onChange={e => setStage(+e.target.value as 1 | 2 | 3)}>
              <option value={1}>1 — 16 аппаратов</option>
              <option value={2}>2 — 32 аппарата</option>
              <option value={3}>3 — все 48</option>
            </select>
          </label>
        </Field>
      </div>

      <table className="edit-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Плоскость</th>
            <th>Slot, °</th>
            <th>Очередь</th>
            <th />
          </tr>
        </thead>
        <tbody>
          {sats.length === 0 && (
            <tr>
              <td colSpan={5} className="muted">
                Спутников нет. Нажмите «+ добавить».
              </td>
            </tr>
          )}
          {sats.map((s, i) => {
            const ierr = errorsForItem(errors, "satellites", i);
            const errFor = (k: string) =>
              ierr.find(e => e.path.endsWith("." + k))?.message;
            return (
              <tr key={i} className={ierr.length ? "row-error" : ""}>
                <td>
                  <Field error={errFor("id")}>
                    <input value={s.id} onChange={e => updSat(i, "id", e.target.value)} />
                  </Field>
                </td>
                <td>
                  <Field error={errFor("plane_id")}>
                    <select value={s.plane_id}
                            onChange={e => updSat(i, "plane_id", e.target.value)}>
                      <option value="">— выберите —</option>
                      {planes.map(p => (
                        <option key={p.id} value={p.id}>{p.id}</option>
                      ))}
                    </select>
                  </Field>
                </td>
                <td>
                  <Field error={errFor("slot_deg")}>
                    <input type="number" step="0.1" value={s.slot_deg}
                           onChange={e => updSat(i, "slot_deg", +e.target.value)} />
                  </Field>
                </td>
                <td>
                  <Field error={errFor("launch_batch")}>
                    <select value={s.launch_batch}
                            onChange={e => updSat(i, "launch_batch", +e.target.value)}>
                      <option value={1}>1</option>
                      <option value={2}>2</option>
                      <option value={3}>3</option>
                    </select>
                  </Field>
                </td>
                <td>
                  <button className="btn tiny danger" onClick={() => removeSat(i)}>−</button>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <div className="batches-summary">
        {([1, 2, 3] as const).map(b => (
          <div key={b} className="batch-card">
            <b>Очередь {b}</b>
            <span> — {batches[b].length} аппаратов</span>
            {d.launch_stage >= b
              ? <span className="ok"> · включена</span>
              : <span className="muted"> · выключена</span>}
          </div>
        ))}
      </div>
    </div>
  );
}
