// app/features/scenario/FailuresTab.vue
<script setup lang="ts">
import type { RouteEntry, Scenario } from '~~/shared/types/scenario'
import type { ValidationError } from '~~/shared/utils/validate'

import { fmtClock } from '~~/shared/utils/format'
import { hasPath } from '~~/shared/utils/routes'

import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Card } from '~/components/ui/card'
import { Input } from '~/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'

const props = defineProps<{
  scenario: Scenario
  errors: ValidationError[]
  routes?: null | Record<string, RouteEntry[]>
  tS?: number
}>()
const emit = defineEmits<{ update: [s: Scenario] }>()

const query = ref('')

const bySat = computed(() => {
  const m = new Map<string, { start_s: number, end_s: number, idx: number }[]>()
  for (const s of props.scenario.design.satellites) m.set(s.id, [])
  props.scenario.failures.forEach((f, idx) => {
    const list = m.get(f.satellite_id)
    if (list)
      list.push({ ...f, idx })
    else m.set(f.satellite_id, [{ ...f, idx }])
  })
  return m
})

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase()
  const all = Array.from(bySat.value.entries())
  if (!q)
    return all
  return all.filter(([sid]) => sid.toLowerCase().includes(q))
})

// Подсветка «в текущем маршруте» (PLAN 1.3).
const inRoute = computed(() => {
  const set = new Set<string>()
  if (!props.routes)
    return set
  for (const entries of Object.values(props.routes)) {
    const entry = entries.find(e => e.t_s === (props.tS ?? 0))
    if (entry && hasPath(entry.path)) {
      for (const id of entry.path) set.add(id)
    }
  }
  return set
})

function add(satId: string) {
  const horizon = props.scenario.environment.horizon_s
  emit('update', {
    ...props.scenario,
    failures: [...props.scenario.failures, {
      end_s: Math.min(3600, horizon),
      satellite_id: satId,
      start_s: 0,
    }],
  })
}

function remove(idx: number) {
  emit('update', { ...props.scenario, failures: props.scenario.failures.filter((_, k) => k !== idx) })
}

function upd(idx: number, k: 'end_s' | 'start_s', v: number) {
  emit('update', {
    ...props.scenario,
    failures: props.scenario.failures.map((f, k2) => (k2 === idx ? { ...f, [k]: v } : f)),
  })
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <div class="flex items-center justify-between gap-2">
      <h3 class="text-sm font-medium">Отказы спутников</h3>
      <Input v-model="query" placeholder="Поиск по ID…" class="max-w-56" />
    </div>
    <p v-if="!scenario.design.satellites.length" class="text-sm text-mist">
      Сначала добавьте спутники на вкладке «Очереди и спутники».
    </p>
    <div class="flex flex-col gap-3">
      <Card v-for="[sid, list] in filtered" :key="sid" class="p-3">
        <div class="mb-2 flex items-center gap-2">
          <b>{{ sid }}</b>
          <span class="text-xs text-mist">— отказов: {{ list.length }}</span>
          <Badge v-if="inRoute.has(sid)" class="ml-1">в маршруте</Badge>
          <Button size="sm" variant="secondary" class="ml-auto" @click="add(sid)">+ отказ</Button>
        </div>
        <p v-if="!list.length" class="text-xs text-mist">Отказов нет</p>
        <Table v-else>
          <TableHeader>
            <TableRow>
              <TableHead>Начало, с</TableHead>
              <TableHead>ЧЧ:ММ:СС</TableHead>
              <TableHead>Конец, с</TableHead>
              <TableHead>ЧЧ:ММ:СС</TableHead>
              <TableHead class="w-12" />
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow v-for="f in list" :key="f.idx">
              <TableCell><Input type="number" step="60" :model-value="f.start_s" @update:model-value="upd(f.idx, 'start_s', Number($event))" /></TableCell>
              <TableCell class="text-xs text-mist">{{ fmtClock(f.start_s) }}</TableCell>
              <TableCell><Input type="number" step="60" :model-value="f.end_s" @update:model-value="upd(f.idx, 'end_s', Number($event))" /></TableCell>
              <TableCell class="text-xs text-mist">{{ fmtClock(f.end_s) }}</TableCell>
              <TableCell><Button size="sm" variant="destructive" @click="remove(f.idx)">−</Button></TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Card>
    </div>
  </div>
</template>

// src/components/FailuresTab.tsx
import { Field, ListHeader } from "./Field";
import { fmtClock } from "../utils/format";
import type { Scenario } from "../types";
import type { ValidationError } from "../utils/validate";
import { errorsForItem } from "../utils/validate";

export default function FailuresTab({
  scenario, errors, onChange,
}: {
  scenario: Scenario;
  errors: ValidationError[];
  onChange: (s: Scenario) => void;
}) {
  const horizon = scenario.environment.horizon_s;

  // группировка отказов по спутнику
  const bySat = new Map<string, { start_s: number; end_s: number; idx: number }[]>();
  scenario.design.satellites.forEach(s => bySat.set(s.id, []));
  scenario.failures.forEach((f, idx) => {
    if (!bySat.has(f.satellite_id)) bySat.set(f.satellite_id, []);
    bySat.get(f.satellite_id)!.push({ ...f, idx });
  });

  function add(satId: string) {
    onChange({
      ...scenario,
      failures: [...scenario.failures, {
        satellite_id: satId, start_s: 0, end_s: Math.min(3600, horizon),
      }],
    });
  }

  function remove(idx: number) {
    onChange({
      ...scenario,
      failures: scenario.failures.filter((_, k) => k !== idx),
    });
  }

  function upd(idx: number, k: "start_s" | "end_s", v: number) {
    const next = scenario.failures.map((f, k2) =>
      k2 === idx ? { ...f, [k]: v } : f,
    );
    onChange({ ...scenario, failures: next });
  }

  return (
    <div className="tab-pane">
      <ListHeader title="Отказы спутников" errors={errors} />

      {scenario.design.satellites.length === 0 && (
        <p className="muted">
          Сначала добавьте спутники на вкладке «Очереди и спутники».
        </p>
      )}

      <div className="failure-groups">
        {Array.from(bySat.entries()).map(([sid, list]) => (
          <div key={sid} className="failure-group">
            <div className="failure-group-header">
              <b>{sid}</b>
              <span className="muted"> — отказов: {list.length}</span>
              <button className="btn tiny" onClick={() => add(sid)}>+ отказ</button>
            </div>

            {list.length === 0 && (
              <div className="muted small">Отказов нет</div>
            )}

            <table className="edit-table small">
              <thead>
                <tr>
                  <th>Начало, с</th>
                  <th>ЧЧ:ММ:СС</th>
                  <th>Конец, с</th>
                  <th>ЧЧ:ММ:СС</th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {list.map((f, k) => {
                  const ierr = errorsForItem(errors, "failures", f.idx);
                  const errMsg = ierr[0]?.message;
                  return (
                    <tr key={k} className={ierr.length ? "row-error" : ""}>
                      <td>
                        <Field error={
                          ierr.find(e => e.path.endsWith(".start_s"))?.message
                            || errMsg
                        }>
                          <input type="number" step="60" value={f.start_s}
                                 onChange={e => upd(f.idx, "start_s", +e.target.value)} />
                        </Field>
                      </td>
                      <td className="muted">{fmtClock(f.start_s)}</td>
                      <td>
                        <Field error={
                          ierr.find(e => e.path.endsWith(".end_s"))?.message
                            || errMsg
                        }>
                          <input type="number" step="60" value={f.end_s}
                                 onChange={e => upd(f.idx, "end_s", +e.target.value)} />
                        </Field>
                      </td>
                      <td className="muted">{fmtClock(f.end_s)}</td>
                      <td>
                        <button className="btn tiny danger"
                                onClick={() => remove(f.idx)}>−</button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ))}
      </div>
    </div>
  );
}
