// app/features/scenario/GatewayOutagesTab.vue
<script setup lang="ts">
import type { Scenario } from '~~/shared/types/scenario'
import type { ValidationError } from '~~/shared/utils/validate'

import { fmtClock } from '~~/shared/utils/format'

import { Button } from '~/components/ui/button'
import { Card } from '~/components/ui/card'
import { Input } from '~/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'

const props = defineProps<{ scenario: Scenario, errors: ValidationError[] }>()
const emit = defineEmits<{ update: [s: Scenario] }>()

const gateways = computed(() => props.scenario.ground_sites.filter(g => g.role === 'gateway'))

const byGw = computed(() => {
  const m = new Map<string, { start_s: number, end_s: number, idx: number }[]>()
  for (const g of gateways.value) m.set(g.id, [])
  props.scenario.gateway_outages.forEach((f, idx) => {
    const list = m.get(f.gateway_id)
    if (list)
      list.push({ ...f, idx })
    else m.set(f.gateway_id, [{ ...f, idx }])
  })
  return m
})

function add(gwId: string) {
  const horizon = props.scenario.environment.horizon_s
  emit('update', {
    ...props.scenario,
    gateway_outages: [...props.scenario.gateway_outages, {
      end_s: Math.min(3600, horizon),
      gateway_id: gwId,
      start_s: 0,
    }],
  })
}

function remove(idx: number) {
  emit('update', { ...props.scenario, gateway_outages: props.scenario.gateway_outages.filter((_, k) => k !== idx) })
}

function upd(idx: number, k: 'end_s' | 'start_s', v: number) {
  emit('update', {
    ...props.scenario,
    gateway_outages: props.scenario.gateway_outages.map((f, k2) => (k2 === idx ? { ...f, [k]: v } : f)),
  })
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <h3 class="text-sm font-medium">Отказы шлюзов</h3>
    <p v-if="!gateways.length" class="text-sm text-mist">
      Сначала добавьте шлюзы на вкладке «Наземные пункты».
    </p>
    <div class="flex flex-col gap-3">
      <Card v-for="[gid, list] in byGw" :key="gid" class="p-3">
        <div class="mb-2 flex items-center gap-2">
          <b>{{ gid }}</b>
          <span class="text-xs text-mist">— отказов: {{ list.length }}</span>
          <Button size="sm" variant="secondary" class="ml-auto" @click="add(gid)">+ отказ</Button>
        </div>
        <p v-if="!list.length" class="text-xs text-mist">Отказов нет</p>
        <Table v-else>
          <TableHeader>
            <TableRow>
              <TableHead>Начало, с</TableHead>
              <TableHead>ЧЧ:ММ:СС</TableHead>
              <TableHead>Конец, с</TableHead>
              <TableHead>ЧЧ:ММ:СС</TableHead>
              <TableHead class="w-12" />
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow v-for="f in list" :key="f.idx">
              <TableCell><Input type="number" step="60" :model-value="f.start_s" @update:model-value="upd(f.idx, 'start_s', Number($event))" /></TableCell>
              <TableCell class="text-xs text-mist">{{ fmtClock(f.start_s) }}</TableCell>
              <TableCell><Input type="number" step="60" :model-value="f.end_s" @update:model-value="upd(f.idx, 'end_s', Number($event))" /></TableCell>
              <TableCell class="text-xs text-mist">{{ fmtClock(f.end_s) }}</TableCell>
              <TableCell><Button size="sm" variant="destructive" @click="remove(f.idx)">−</Button></TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Card>
    </div>
  </div>
</template>

// src/components/GatewayOutagesTab.tsx
import { Field, ListHeader } from "./Field";
import { fmtClock } from "../utils/format";
import type { Scenario } from "../types";
import type { ValidationError } from "../utils/validate";
import { errorsForItem } from "../utils/validate";

export default function GatewayOutagesTab({
  scenario, errors, onChange,
}: {
  scenario: Scenario;
  errors: ValidationError[];
  onChange: (s: Scenario) => void;
}) {
  const horizon = scenario.environment.horizon_s;
  const gateways = scenario.ground_sites.filter(g => g.role === "gateway");

  const byGw = new Map<string, { start_s: number; end_s: number; idx: number }[]>();
  gateways.forEach(g => byGw.set(g.id, []));
  scenario.gateway_outages.forEach((f, idx) => {
    if (!byGw.has(f.gateway_id)) byGw.set(f.gateway_id, []);
    byGw.get(f.gateway_id)!.push({ ...f, idx });
  });

  function add(gwId: string) {
    onChange({
      ...scenario,
      gateway_outages: [...scenario.gateway_outages, {
        gateway_id: gwId, start_s: 0, end_s: Math.min(3600, horizon),
      }],
    });
  }

  function remove(idx: number) {
    onChange({
      ...scenario,
      gateway_outages: scenario.gateway_outages.filter((_, k) => k !== idx),
    });
  }

  function upd(idx: number, k: "start_s" | "end_s", v: number) {
    const next = scenario.gateway_outages.map((f, k2) =>
      k2 === idx ? { ...f, [k]: v } : f,
    );
    onChange({ ...scenario, gateway_outages: next });
  }

  return (
    <div className="tab-pane">
      <ListHeader title="Отказы шлюзов" errors={errors} />

      {gateways.length === 0 && (
        <p className="muted">
          Сначала добавьте шлюзы на вкладке «Наземные пункты».
        </p>
      )}

      <div className="failure-groups">
        {Array.from(byGw.entries()).map(([gid, list]) => (
          <div key={gid} className="failure-group">
            <div className="failure-group-header">
              <b>{gid}</b>
              <span className="muted"> — отказов: {list.length}</span>
              <button className="btn tiny" onClick={() => add(gid)}>+ отказ</button>
            </div>

            {list.length === 0 && (
              <div className="muted small">Отказов нет</div>
            )}

            <table className="edit-table small">
              <thead>
                <tr>
                  <th>Начало, с</th>
                  <th>ЧЧ:ММ:СС</th>
                  <th>Конец, с</th>
                  <th>ЧЧ:ММ:СС</th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {list.map((f, k) => {
                  const ierr = errorsForItem(errors, "gateway_outages", f.idx);
                  const errMsg = ierr[0]?.message;
                  return (
                    <tr key={k} className={ierr.length ? "row-error" : ""}>
                      <td>
                        <Field error={
                          ierr.find(e => e.path.endsWith(".start_s"))?.message
                            || errMsg
                        }>
                          <input type="number" step="60" value={f.start_s}
                                 onChange={e => upd(f.idx, "start_s", +e.target.value)} />
                        </Field>
                      </td>
                      <td className="muted">{fmtClock(f.start_s)}</td>
                      <td>
                        <Field error={
                          ierr.find(e => e.path.endsWith(".end_s"))?.message
                            || errMsg
                        }>
                          <input type="number" step="60" value={f.end_s}
                                 onChange={e => upd(f.idx, "end_s", +e.target.value)} />
                        </Field>
                      </td>
                      <td className="muted">{fmtClock(f.end_s)}</td>
                      <td>
                        <button className="btn tiny danger"
                                onClick={() => remove(f.idx)}>−</button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ))}
      </div>
    </div>
  );
}
