// app/features/scenario/PlanesTab.vue
<script setup lang="ts">
import type { Scenario } from '~~/shared/types/scenario'
import type { ValidationError } from '~~/shared/utils/validate'

import { PlusIcon } from 'lucide-vue-next'
import { errorsForItem } from '~~/shared/utils/validate'

import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'

const props = defineProps<{ scenario: Scenario, errors: ValidationError[] }>()
const emit = defineEmits<{ update: [s: Scenario] }>()

function upd(i: number, k: 'id' | 'phase_deg' | 'raan_deg', v: number | string) {
  const planes = props.scenario.design.planes.map((p, k2) => (k2 === i ? { ...p, [k]: v } : p))
  emit('update', { ...props.scenario, design: { ...props.scenario.design, planes } })
}

function add() {
  const planes = props.scenario.design.planes
  const id = `P${planes.length + 1}`
  emit('update', {
    ...props.scenario,
    design: { ...props.scenario.design, planes: [...planes, { id, phase_deg: 0, raan_deg: 0 }] },
  })
}

function remove(i: number) {
  emit('update', {
    ...props.scenario,
    design: { ...props.scenario.design, planes: props.scenario.design.planes.filter((_, k) => k !== i) },
  })
}

function errFor(i: number, k: string): string | undefined {
  return errorsForItem(props.errors, 'planes', i).find(e => e.path.endsWith(`.${k}`))?.message
}

function hasRowError(i: number): boolean {
  return errorsForItem(props.errors, 'planes', i).length > 0
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <div class="flex items-center justify-between">
      <h3 class="text-sm font-medium">Орбитальные плоскости</h3>
      <Button size="sm" variant="secondary" @click="add">
        <PlusIcon data-icon="inline-start" />Добавить
      </Button>
    </div>
    <p v-if="!scenario.design.planes.length" class="text-sm text-mist">
      Плоскостей нет. Нажмите «Добавить».
    </p>
    <Table v-else>
      <TableHeader>
        <TableRow>
          <TableHead>ID</TableHead>
          <TableHead>RAAN, °</TableHead>
          <TableHead>Phase, °</TableHead>
          <TableHead class="w-12" />
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow v-for="(p, i) in scenario.design.planes" :key="i" :data-invalid="hasRowError(i) || undefined">
          <TableCell>
            <Input :model-value="p.id" :aria-invalid="!!errFor(i, 'id')" @update:model-value="upd(i, 'id', String($event))" />
            <p v-if="errFor(i, 'id')" class="mt-1 text-xs text-primary">{{ errFor(i, 'id') }}</p>
          </TableCell>
          <TableCell>
            <Input type="number" step="0.1" :model-value="p.raan_deg" :aria-invalid="!!errFor(i, 'raan_deg')" @update:model-value="upd(i, 'raan_deg', Number($event))" />
            <p v-if="errFor(i, 'raan_deg')" class="mt-1 text-xs text-primary">{{ errFor(i, 'raan_deg') }}</p>
          </TableCell>
          <TableCell>
            <Input type="number" step="0.1" :model-value="p.phase_deg" :aria-invalid="!!errFor(i, 'phase_deg')" @update:model-value="upd(i, 'phase_deg', Number($event))" />
            <p v-if="errFor(i, 'phase_deg')" class="mt-1 text-xs text-primary">{{ errFor(i, 'phase_deg') }}</p>
          </TableCell>
          <TableCell>
            <Button size="sm" variant="destructive" @click="remove(i)">−</Button>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>
  </div>
</template>

// src/components/PlanesTab.tsx
import { Field, ListHeader } from "./Field";
import type { Scenario } from "../types";
import type { ValidationError } from "../utils/validate";
import { errorsForItem } from "../utils/validate";

export default function PlanesTab({
  scenario, errors, onChange,
}: {
  scenario: Scenario;
  errors: ValidationError[];
  onChange: (s: Scenario) => void;
}) {
  const planes = scenario.design.planes;

  function upd(i: number, k: "id" | "raan_deg" | "phase_deg", v: any) {
    const next = planes.map((p, k2) => (k2 === i ? { ...p, [k]: v } : p));
    onChange({ ...scenario, design: { ...scenario.design, planes: next } });
  }

  function add() {
    const id = `P${planes.length + 1}`;
    onChange({
      ...scenario,
      design: {
        ...scenario.design,
        planes: [...planes, { id, raan_deg: 0, phase_deg: 0 }],
      },
    });
  }

  function remove(i: number) {
    onChange({
      ...scenario,
      design: { ...scenario.design, planes: planes.filter((_, k) => k !== i) },
    });
  }

  return (
    <div className="tab-pane">
      <ListHeader title="Орбитальные плоскости" errors={errors} onAdd={add} />

      {planes.length === 0 && (
        <p className="muted">Плоскостей нет. Нажмите «+ добавить».</p>
      )}

      <table className="edit-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>RAAN, °</th>
            <th>Phase, °</th>
            <th />
          </tr>
        </thead>
        <tbody>
          {planes.map((p, i) => {
            const ierr = errorsForItem(errors, "planes", i);
            const errFor = (k: string) =>
              ierr.find(e => e.path.endsWith("." + k))?.message;
            return (
              <tr key={i} className={ierr.length ? "row-error" : ""}>
                <td>
                  <Field error={errFor("id")}>
                    <input value={p.id} onChange={e => upd(i, "id", e.target.value)} />
                  </Field>
                </td>
                <td>
                  <Field error={errFor("raan_deg")}>
                    <input type="number" step="0.1" value={p.raan_deg}
                           onChange={e => upd(i, "raan_deg", +e.target.value)} />
                  </Field>
                </td>
                <td>
                  <Field error={errFor("phase_deg")}>
                    <input type="number" step="0.1" value={p.phase_deg}
                           onChange={e => upd(i, "phase_deg", +e.target.value)} />
                  </Field>
                </td>
                <td>
                  <button className="btn tiny danger" onClick={() => remove(i)}>−</button>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}
